name: boeoeg_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

#ersten 3 sind die version und +1 ist build

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  cupertino_icons: 
  cupertino_calendar: ^1.0.0
  http: ^0.13.4
  hive_flutter:
  flutter_local_notifications: ^9.4.0
  rxdart: ^0.27.3
  flutter_native_timezone: ^2.0.0
  device_calendar: ^4.2.0
  #path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0

flutter_icons:
  image_path: "images/cliquenFoto.jpg"
  image_path_android: "images/cliquenFoto.jpg"
  image_path_ios: "images/cliquenFoto.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - images/insta.PNG
  
